### ISSUE TITLE
VS Code becomes VERY slow or crashes when writing Javascript code with JSX syntax

### ISSUE THREAD

**Issue by hristod** [VSCodeVim/Vim#2112]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: 1.17.2
- **VsCodeVim Version**: 0.10.2
- **OS**: Windows 10

**What happened**:

When I have a long line of text, expecially a JSX element with a parameter with long text in quotes, VS Code starts to work very slowly or completely crashes. This doesn't happen when Vim for VS Code is disabled.

**What did you expect to happen**: 
Should work normally - not slowing down / crashing editor.

**How to reproduce it**:
Open a JSX file with VS Code with Vim extension enabled, try to edit a long line.

**Comment by binlaniua** [comment]
+1

**Comment by hristod** [comment]
Please, if anyone has a workaround at least, please let us know! I have to disable the plugin if I write something with longer lines or switch to Vim temporary, which is not cool at all...

**Comment by AlexanderOtavka** [comment]
I have a repro case!

Try editing this in a css file:

```css
.gear::before {
  content: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#5dc2af" d="M12,15.5A3.5,3.5 0 0,1 8.5,12A3.5,3.5 0 0,1 12,8.5A3.5,3.5 0 0,1 15.5,12A3.5,3.5 0 0,1 12,15.5M19.43,12.97C19.47,12.65 19.5,12.33 19.5,12C19.5,11.67 19.47,11.34 19.43,11L21.54,9.37C21.73,9.22 21.78,8.95 21.66,8.73L19.66,5.27C19.54,5.05 19.27,4.96 19.05,5.05L16.56,6.05C16.04,5.66 15.5,5.32 14.87,5.07L14.5,2.42C14.46,2.18 14.25,2 14,2H10C9.75,2 9.54,2.18 9.5,2.42L9.13,5.07C8.5,5.32 7.96,5.66 7.44,6.05L4.95,5.05C4.73,4.96 4.46,5.05 4.34,5.27L2.34,8.73C2.21,8.95 2.27,9.22 2.46,9.37L4.57,11C4.53,11.34 4.5,11.67 4.5,12C4.5,12.33 4.53,12.65 4.57,12.97L2.46,14.63C2.27,14.78 2.21,15.05 2.34,15.27L4.34,18.73C4.46,18.95 4.73,19.03 4.95,18.95L7.44,17.94C7.96,18.34 8.5,18.68 9.13,18.93L9.5,21.58C9.54,21.82 9.75,22 10,22H14C14.25,22 14.46,21.82 14.5,21.58L14.87,18.93C15.5,18.67 16.04,18.34 16.56,17.94L19.05,18.95C19.27,19.03 19.54,18.95 19.66,18.73L21.66,15.27C21.78,15.05 21.73,14.78 21.54,14.63L19.43,12.97Z"/></svg>');
}
```
